create table public.plano_aula_solicitacao (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  disciplina public.disciplinas not null,
  tema_aula text not null,
  etapa_ensino public.etapas_ensino not null,
  tempo_aula bigint not null,
  constraint plano_aula_solicitacao_pkey primary key (id),
  constraint plano_aula_solicitacao_tempo_aula_check check (
    (
      (tempo_aula > 0)
      and (tempo_aula < 140)
    )
  )
) TABLESPACE pg_default;

create table public.plano_aula_gerado (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  solicitacao_id bigint not null,
  introducao text not null,
  objetivo text not null,
  roteiro jsonb not null,
  rubrica jsonb not null,
  constraint plano_aula_gerado_pkey primary key (id),
  constraint plano_aula_gerado_solicitacao_id_fkey foreign KEY (solicitacao_id) references plano_aula_solicitacao (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;